config/routes.rb
Rails.application.routes.draw do
	root "pages#index"

	resources :users, only: [:create, :update, :edit] do
		scope module: "users" do
			resources :passports, only: [:show], as: "u_passport"
		end
	end
  resources :passports, only: [:index, :show]
	resources :user_passports, only: [:create, :destroy]
	resources :groups, only: [:index, :show, :new, :create]
	resources :memberships, only: [:destroy, :create]

	namespace :admin do
		resources :users, only: [:index]
	end

	namespace :api, defaults: {format: :json} do
		namespace :v1 do
			delete "/visits", to: "visits#destroy"
			resources :visits, only: [:index, :create]
		end
	end

	get "/auth/:provider/callback", to: "sessions#create"

	get  "/dashboard", to: "users#show", as: "user_dashboard"
	get  "/auth/facebook/callback", to: "sessions#create"
	post "/auth/facebook/callback", to: "sessions#create"
	get  "/auth/facebook", as: "facebook_login"
	get  "/auth/failure",    to: redirect("/")
	get  "/login",  			   to: "sessions#new", as: "login"
	post "/login",  			   to: "sessions#create_from_email"
	get  "/logout", 			   to: "sessions#destroy"
	get  "/admin/dashboard", to: "admin#show", as: "admin_dashboard"
	get  "/errors/404",      to: "errors#show", as: "errors_404"
end

app/views/admin/show.html.erb
<div class="container page-header">
  <i class="fa fa-futbol-o fa-2x active" aria-hidden="true"></i>
  <p>Admin Dashboard</p>

<div class="row">

  <div class="card col-md-4 col-centered">
    <div class="card-block passport">
      <i class="fa fa-users fa-2x users" aria-hidden="true"></i>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h5 class="card-title">
          <%= link_to "#{@users.count} Total User".pluralize, admin_users_path %>
        </h5>
        <h6 class="card-subtitle text-muted">
          have a total of<br />
        </h6>
        <h5 class="card-title">
          <%= "#{@ups.count} Passport".pluralize %>
        </h5>
      </li>
    </ul>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h6 class="text-muted"><%= "#{User.average_passports} Passport".pluralize %> per User</h6>
      </li>
    </ul>
  </div>

  <div class="card col-md-4 col-centered">
    <div class="card-block passport">
      <i class="fa fa-shopping-bag fa-2x visits" aria-hidden="true"></i>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h5 class="card-title">
          <%= "#{@visits.count} Visit".pluralize(@visits.count) %>
        </h5>
        <h6 class="card-subtitle text-muted">
          over<br />
        </h6>
        <h5 class="card-title">
          <%= "#{@venues.count} Venue".pluralize(@venues.count) %>
        </h5>
      </li>
    </ul>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h6 class="text-muted"><%= "#{Visit.average_visits} Visit".pluralize %> per Venue</h6>
      </li>
    </ul>

  </div>

  <div class="card col-md-4 col-centered">
    <div class="card-block passport">
      <i class="fa fa-keyboard-o fa-2x groups" aria-hidden="true"></i>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h5 class="card-title">
          <%= "#{@groups.count} Group".pluralize(@groups.count) %>
        </h5>
        <h6 class="card-subtitle text-muted">
          and<br />
        </h6>
        <h5 class="card-title">
          <%= "#{@passports.count} Passport".pluralize(@passports.count) %>
        </h5>
      </li>
    </ul>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h6 class="text-muted">Another Statistic Per Statistic</h6>
      </li>
    </ul>
  </div>
</div>
</div>