config/routes.rb
Rails.application.routes.draw do
	root "pages#index"

	resources :users, only: [:create, :update, :edit] do
		scope module: "users" do
			resources :passports, only: [:show], as: "u_passport"
		end
	end
  resources :passports, only: [:index, :show]
	resources :user_passports, only: [:create, :destroy]
	resources :groups, only: [:index, :show, :new, :create]
	resources :memberships, only: [:destroy, :create]

	namespace :admin do
		resources :users, only: [:index]
	end

	namespace :api, defaults: {format: :json} do
		namespace :v1 do
			delete "/visits", to: "visits#destroy"
			resources :visits, only: [:index, :create]
		end
	end

	get "/auth/:provider/callback", to: "sessions#create"

	get  "/dashboard", to: "users#show", as: "user_dashboard"
	get  "/auth/facebook/callback", to: "sessions#create"
	post "/auth/facebook/callback", to: "sessions#create"
	get  "/auth/facebook", as: "facebook_login"
	get  "/auth/failure",    to: redirect("/")
	get  "/login",  			   to: "sessions#new", as: "login"
	post "/login",  			   to: "sessions#create_from_email"
	get  "/logout", 			   to: "sessions#destroy"
	get  "/admin/dashboard", to: "admin#show", as: "admin_dashboard"
	get  "/errors/404",      to: "errors#show", as: "errors_404"
end

app/models/group.rb
class Group < ActiveRecord::Base
  include Formatter
  after_create :membership_association

  belongs_to :passport
  has_many   :venues, through: :passport
  has_many   :memberships,  dependent: :destroy
  has_many   :users, through: :memberships
  validates :name, presence: true, uniqueness: true
  validates :passport_id, presence: true


  def membership_count
    users.count
  end

  private
  def membership_association
    Membership.create(group_id: self.id, user_id: self.user_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find_by(id: params[:id])
    @venues = @group.passport.venues
    @users = @group.users
    @up = UserPassport.where(passport_id: @group.passport_id)
    @visits = YelpVenue.up_visits_group(@up)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      UserPassport.group_created(group_params)
      flash[:success] = "#{@group.name} Group Created!"
      redirect_to user_dashboard_path
    else
      flash[:danger] = @group.errors.full_messages.join(" ")
      redirect_to :back
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, :passport_id, :user_id)
  end
end

app/views/groups/index.html.erb
<div class="container">
  <div class="page-header">
    <i class="fa fa-user-plus fa-2x active" aria-hidden="true"></i>
    <p>Do you need some friends?</p>
    <span>But don't be a weirdo stalker.</span><br />
    <%= link_to "Create a New Group!", new_group_path %>
  </div>
  <% @groups.each do |g| %>
  <div class="card">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
      <h5 class="cart-title"><%= link_to g.name, group_path(g) %></h5>
      <p class="list-group-item-text muted-text"><%= g.passport.name %></p>
    </li>
    </ul>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h6 class="list-group-item-heading"><%= "#{g.membership_count} Member".pluralize(g.membership_count) %> </h6>
        <p class="list-group-item-text">Established <%= Formatter.parse(g.created_at) %></p>
      </li>
    </ul>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <% if  current_user && current_user.group_member?(g) %>
          <%= link_to "Check Out Group Progress", group_path(g), class:"card-link"%>
        <% elsif current_user %>
          <%= button_to "Join Group!", memberships_path(group_id: g.id, user_id: current_user.id), name: "add-to-account", class: "add-to-account" %>
        <% else %>
          <p class="list-group-item-text"><%= link_to "Sign up or Sign In!", "#" , data: {toggle: "modal", target: "#loginModal"}%></p>
        <% end %>
      </li>
    </ul>
  </div>

  <% end %>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="page-header">
		<i class="fa fa-users fa-2x active" aria-hidden="true"></i>
		<p>Creating a new group?!</p>
	</div>
  <div class=" col-md-4 col-md-offset-4">

  <%= form_for @group do |f| %>
    <%= f.label :name, "Name" %>
    <% if current_user %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    <% end %>
    <%= f.text_field :name, placeholder: "Group Name", class:"form-control" %>
    <%= f.label :pasport_id, "What passport does this group have?", class: "new-group-passport-form" %>
    <%= collection_select(:group, :passport_id, Passport.all, :id, :name, {prompt: true}, {class:"form-control", id: "group-select"}) %>
    <%= f.submit "Create Group!", class:"btn btn-primary new-group-passport-form" %>
  <% end %>
</div>
</div>

app/views/groups/show.html.erb
<div class="container">
	<div class="page-header">
		<i class="fa fa-tachometer fa-2x active" aria-hidden="true"></i>
		<p><%= @group.name %></p>
		<div><%= link_to @group.passport.name, passport_path(@group.passport) %></div>
		<% if current_user && current_user.has_passport?(@group.passport) %>
			<div><%= link_to "Your Progress", user_u_passport_path(user_id: current_user.id, id: @group.passport.id), class:"card-link"%></div>
		<% end %>
		<div><br />Click the button to filter <br />to group unvisited spots</div>

		<button type="button" class="btn btn-primary group-collapse">FILTER VISITED VENUES</button>

	</div>


	<table id="group-show" class="table table-bordered table-group">
		<thead class="thead-inverse">
			<tr>
				<th class="group-show-col-1">Venue</th>
				<% @users.each do |user| %>
				<th><%= user.truncated_name %></th>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<% @venues.each_with_index do |venue, index| %>
			<tr>
				<td>
					<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#special-<%= index %>" aria-expanded="false" aria-controls="collapseTwo">
						<b><%= venue.name %></b> - Specials<br />
					</a>
					<div id="special-<%= index %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
						<%= venue.address %><br />
						<span class="group-show-special"><%= venue.passport_specials(@group.passport) %></span>
					</div>
					<%= link_to venue.yurl, target:"_blank" do %>
					<%= image_tag venue.ratings %><br /><%= venue.review_number %> Reviews
					<% end %>
				</td>
				<% @users.each do |user| %>
				<td id="<%= "#{venue.y_id}-#{user.id}" %>"></td>
				<% end %>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<script>
$(document).ready(function() {
	highlightVisits();

	$('.group-collapse').click(function(){
		$('.visited-cell').parent().toggle(500)
	})

})

function highlightVisits(){
	$("<%= @visits %>").addClass('visited-cell')
}
</script