config/routes.rb
Rails.application.routes.draw do
	root "pages#index"

	resources :users, only: [:create, :update, :edit] do
		scope module: "users" do
			resources :passports, only: [:show], as: "u_passport"
		end
	end
  resources :passports, only: [:index, :show]
	resources :user_passports, only: [:create, :destroy]
	resources :groups, only: [:index, :show, :new, :create]
	resources :memberships, only: [:destroy, :create]

	namespace :admin do
		resources :users, only: [:index]
	end

	namespace :api, defaults: {format: :json} do
		namespace :v1 do
			delete "/visits", to: "visits#destroy"
			resources :visits, only: [:index, :create]
		end
	end

	get "/auth/:provider/callback", to: "sessions#create"

	get  "/dashboard", to: "users#show", as: "user_dashboard"
	get  "/auth/facebook/callback", to: "sessions#create"
	post "/auth/facebook/callback", to: "sessions#create"
	get  "/auth/facebook", as: "facebook_login"
	get  "/auth/failure",    to: redirect("/")
	get  "/login",  			   to: "sessions#new", as: "login"
	post "/login",  			   to: "sessions#create_from_email"
	get  "/logout", 			   to: "sessions#destroy"
	get  "/admin/dashboard", to: "admin#show", as: "admin_dashboard"
	get  "/errors/404",      to: "errors#show", as: "errors_404"
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  validates :password, length: { minimum: 8 }, on: :create

  has_many :memberships
  has_many :groups, through: :memberships

  has_many :user_passports
  has_many :passports, through: :user_passports

  has_many :user_notifications
  has_many :notifications, through: :user_notifications

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :provider, presence: true

  enum role: ["default", "admin"]

  def self.from_omniauth(auth_hash)
    user = find_or_create_by(email: auth_hash['info']['email'], provider: auth_hash['provider'])
    user.name = auth_hash['info']['name']
    user.email = auth_hash['info']['email']
    user.image_url = auth_hash['info']['image']
    user.uid = auth_hash['uid']
    user.password = SecureRandom.hex(9)
    user.save!

    user
  end

  def passport_count
    passports.count
  end

  def group_count
    groups.count
  end

  def update_profile(user_params)
    update(user_params)
  end

  def group_member?(group)
    groups.include?(group)
  end

  def has_passport?(passport)
    passports.include?(passport)
  end

  def truncated_name
    new_name = []
    parts = name.split
    new_name << parts.shift
    if parts.empty?
      return new_name.first
    else
      parts.each do |n|
        new_name << n[0]
      end
    end
    new_name.join(" ")
  end

  def self.average_passports
    (UserPassport.all.count.to_f / User.all.count).round(2)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end
end

app/controllers/users/passports_controller.rb
class Users::PassportsController < ApplicationController
  before_action :require_user
  def show
    @passport = Passport.find(params[:id])
    @venues = @passport.venues
    @up = UserPassport.find_by(user_id: params[:user_id], passport_id: params[:id])
    @visits = YelpVenue.up_visits(@up)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]

  def new
  end

  def show
    @user = current_user
	end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Thanks for signing up!"
      redirect_to user_dashboard_path
    else
      flash[:warning] = @user.errors.full_messages.join("<br />").html_safe
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_profile(user_params)
    flash[:success] = "Yay!"
    redirect_to user_dashboard_path
  end

  private

    def user_params
      params.require(:user).permit(:provider, :email, :password, :name, :image_url)
    end

end

app/views/users/complete.html.erb
<h1>We're almost done!</h1>

<%= form_for @user do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :image_url, "Profile Photo" %>
  <%= f.text_field :image_url %>
  <%= f.submit "Complete Registration!" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="page-header">
    <i class="fa fa-unlock fa-2x active" aria-hidden="true"></i>
    <p>Edit Profile Stuff:</p>
  </div>
  <div class=" col-md-4 col-md-offset-4">
    If you signed in with FaceBook, you can only update your name. The rest of your login information is protected by your Facebook Authorization.
    <%= form_for @user do |f| %>
      <%= f.label :name, "Name", class: "new-group-passport-form" %>
      <%= f.text_field :name, class:"form-control" %>

      <%= f.label :email, "E-Mail", class: "new-group-passport-form" %>
      <%= f.text_field :email, class:"form-control" %>
        <%= f.label :password, class: "new-group-passport-form" %>
        <%= f.password_field :password, class: "form-control" %>
      <%= f.submit "Update Profile!", class:"btn btn-primary new-group-passport-form" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="page-header">
		<i class="fa fa-tachometer fa-2x active" aria-hidden="true"></i>
		<p>Dashboard!</p>
	</div>
	<div class="list-group">
		<div class="list-group-item active">
			<h4 class="list-group-item-heading profile-header">My Profile</h4>
		</div>
	</div>
	<div class="list-group-item profile-body">
		<p>Name: <%= @user.name %><br />
			E-Mail: <%= @user.email %></p>
			<% if @user.provider == "email" %>
			<%= link_to "Edit Profile", edit_user_path(@user), class:"add-btn" %>
			<% end %>
			<!-- <a href="#" class="add-btn">Edit Profile</a> -->
		</div>
		<hr />
		<div class="row">

			<div class="col-md-6">
				<div class="list-group">
					<div class="list-group-item active">

						<h4 class="list-group-item-heading profile-header">My Passports<span class="label label-default label-pill pull-right"><%= @user.passport_count %></span></h4>
						<p><%= link_to "Find a Passport", passports_path %> - <%= link_to "Create a New Passport( COMING SOON! )", "#" %></p>
					</div>
				</div>
				<div class="list-group-item profile-body">
					<% @user.passports.each do |passport| %>
					<div class="passport">
						<%= link_to passport.name, user_u_passport_path(user_id: current_user.id, id: passport.id) %> - <%= button_to "Remove from My Account", user_passport_path(passport) , name: "add-to-account", method: :delete, data: { confirm: "REALLY?!?" } %>
					</div>
					<% end %>
				</div>
			</div>

			<div class="col-md-6">
				<div class="list-group">
					<div class="list-group-item active">
						<h4 class="list-group-item-heading profile-header">My Groups<span class="label label-default label-pill pull-right"><%= @user.group_count %></span></h4>
						<p><%= link_to "Create a New Group", new_group_path %> - <%= link_to "Find a Group", groups_path %></p>
					</div>
				</div>
				<div class="list-group-item profile-body">
					<% @user.groups.each do |group| %>
						<div class="group">
							<%= link_to group.name, group_path(group) %> - <%= group.passport.name %><br /><%= button_to "Leave the Group", membership_path(group) , name: "add-to-account", method: :delete, data: { confirm: "Done with these people?" } %>

						</div>
					<% end %>

				</div>
			</div>

		</div>
	</div>