config/routes.rb
Rails.application.routes.draw do
	root "pages#index"

	resources :users, only: [:create, :update, :edit] do
		scope module: "users" do
			resources :passports, only: [:show], as: "u_passport"
		end
	end
  resources :passports, only: [:index, :show]
	resources :user_passports, only: [:create, :destroy]
	resources :groups, only: [:index, :show, :new, :create]
	resources :memberships, only: [:destroy, :create]

	namespace :admin do
		resources :users, only: [:index]
	end

	namespace :api, defaults: {format: :json} do
		namespace :v1 do
			delete "/visits", to: "visits#destroy"
			resources :visits, only: [:index, :create]
		end
	end

	get "/auth/:provider/callback", to: "sessions#create"

	get  "/dashboard", to: "users#show", as: "user_dashboard"
	get  "/auth/facebook/callback", to: "sessions#create"
	post "/auth/facebook/callback", to: "sessions#create"
	get  "/auth/facebook", as: "facebook_login"
	get  "/auth/failure",    to: redirect("/")
	get  "/login",  			   to: "sessions#new", as: "login"
	post "/login",  			   to: "sessions#create_from_email"
	get  "/logout", 			   to: "sessions#destroy"
	get  "/admin/dashboard", to: "admin#show", as: "admin_dashboard"
	get  "/errors/404",      to: "errors#show", as: "errors_404"
end

app/views/shared/_banner.html.erb
<div class="background-image">
  <div class="container banner-text">
    Are you trying to figure out where to go with your friends?<br />
    <span><%= link_to "Let me help.", passports_path, class: "splash-link" %></span>
  </div>
</div>

app/views/shared/_modal.html.erb
<!-- Login or Register Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-md-6 left-modal">
            <h4 class="modal-title" class="modal-title">Login</h4>
          </div>
          <div class="col-md-6">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" class="modal-title">Register</h4>
          </div>
        </div>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6 left-modal">
            <%= form_for :session, url: login_path do |f| %>
              <%= f.label :email, "E-Mail" %>
              <%= f.text_field :email, placeholder: "E-Mail", class: "form-control" %><br />
              <%= f.label :password, "Password" %>
              <%= f.password_field :password, placeholder: "Password", class: "form-control" %><br />
              <%= f.submit "Let's Go!", class: "btn btn-primary" %>
            <% end %>
            <%= link_to facebook_login_path, class: "btn btn-facebook" do %>
              <i class="fa fa-facebook-official" aria-hidden="true"></i>&nbsp;&nbsp;Continue with Facebook
            <% end %>
            <!-- <div class="fb-login-button" data-max-rows="1" data-size="large" data-show-faces="true" data-auto-logout-link="false"></div> -->
          </div>

          <div class="col-md-6">
            <%= form_for User.new do |f| %>
              <%= f.hidden_field :provider, value: "email" %>
              <%= f.label :name, "Full Name:" %>
              <%= f.text_field :name, placeholder: "Full Name", class: "form-control" %><br>
              <%= f.label :email, "E-Mail Address:" %>
              <%= f.text_field :email, placeholder: "E-Mail", class: "form-control" %><br>
              <%= f.label :password, "Password:" %>
              <%= f.password_field :password, placeholder: "Password", class: "form-control" %><br>
              <%= f.submit "Create New Account!", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>

      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>
<!-- Login or Register Modal -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-dark">
    <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#responsiveCollapse">
      ☰
    </button>
      <div class="container">
      <div class="navbar-header hidden-sm-down">
        <%= link_to "Passport Helper", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-toggleable-sm" id="responsiveCollapse"> <!-- class .navbar-toggleable-* -->
      <div class="pull-md-right" id="spy-nav">
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Passports", passports_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "Groups", groups_path, class:"nav-link" %></li>
          <% if current_admin? %>
          <li class="nav-item"><%= link_to "Admin", admin_dashboard_path, class:"nav-link" %></li>
          <% end %>
          <% if current_user %>
          <li class="nav-item"><%= link_to "Dashboard", user_dashboard_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "Log Out", logout_path, class:"nav-link" %></li>
        </ul>
          <% else %>
        <li class="nav-item"><%= link_to "Login or Register", "#", class:"nav-link", data: {toggle: "modal", target: "#loginModal"} %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbartwo.html.erb
<nav class="navbar navbar-static-top navbar-dark">
<div class="container">


  <button class="navbar-toggler hidden-md-up pull-sm-right pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
    &#9776;
  </button>
  <%= link_to "Passport Helper", root_path, class: "navbar-brand navbar-brand" %>
  <div class="collapse hidden-md-up" id="exCollapsingNavbar">
    <ul class="nav navbar-nav">
      <li class="nav-item"></li>
      <li class="nav-item"><%= link_to "Passports", passports_path, class:"nav-link" %></li>
      <li class="nav-item"><%= link_to "Groups", groups_path, class:"nav-link" %></li>
      <% if current_admin? %>
      <li class="nav-item"><%= link_to "Admin", admin_dashboard_path, class:"nav-link" %></li>
      <% end %>
      <% if current_user %>
      <li class="nav-item"><%= link_to "Dashboard", user_dashboard_path, class:"nav-link" %></li>
      <li class="nav-item"><%= link_to "Log Out", logout_path, class:"nav-link" %></li>
    </ul>
      <% else %>
    <li class="nav-item"><%= link_to "Login or Register", "#", class:"nav-link", data: {toggle: "modal", target: "#loginModal"} %></li>
      <% end %>

    </ul>
  </div>

  <div class="hidden-sm-down pull-md-right">
    <ul class="nav navbar-nav">
      <li class="nav-item"><%= link_to "Passports", passports_path, class:"nav-link" %></li>
      <li class="nav-item"><%= link_to "Groups", groups_path, class:"nav-link" %></li>
      <% if current_admin? %>
      <li class="nav-item"><%= link_to "Admin", admin_dashboard_path, class:"nav-link" %></li>
      <% end %>
      <% if current_user %>
      <li class="nav-item"><%= link_to "Dashboard", user_dashboard_path, class:"nav-link" %></li>
      <li class="nav-item"><%= link_to "Log Out", logout_path, class:"nav-link" %></li>
    </ul>
      <% else %>
    <li class="nav-item"><%= link_to "Login or Register", "#", class:"nav-link", data: {toggle: "modal", target: "#loginModal"} %></li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/shared/_passports.html.erb
<div class="container">
  <% passports.each do |p| %>
  <div class="card">
    <div class="card-block passport">
      <h5 class="card-title"><%= link_to p.name, passport_path(p) %></h5>
      <h6 class="card-subtitle text-muted"><%= link_to "#{p.url}", "http://#{p.url}", target: "_blank" %></h6>
    </div>
    <div class="p-image">
      <img class="card-img-top passport-index-image" src="<%= p.passport_images("348x180") %>" alt="<%= p.name %>" />
    </div>
    <!-- paperclip needs to bring in url and specific szie -->
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h6 class="list-group-item-heading"><%= "#{p.venues.count} Venue".pluralize(p.venues.count) %></h6>
      </li>
      <li class="list-group-item">
        <h6 class="list-group-item-heading">Valid From</h6>
        <p class="list-group-item-text"><%= "#{Formatter.parse(p.start)} to #{Formatter.parse(p.expiration)}" %></p>
      </li>
    </ul>
    <div class="card-block footer">
      <%= link_to "Deets", passport_path(p), class:"card-link" %>
      <% if current_user && current_user.passports.include?(p) %>
        <%= link_to "Your Progress", user_u_passport_path(user_id: current_user.id, id: p.id), class:"card-link"%>
      <% elsif current_user %>
        <%= button_to "Add to My Account", user_passports_path(passport_id: p.id, user_id: current_user.id), name: "add-to-account", class: "add-to-account" %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>